### ISSUE TITLE
Onboard Skribble-connector to Axon-ivy market

### ISSUE THREAD

**Issue by ivy-jh** [axonivy-market/market#427] opened 2024-08-29 08:05 UTC
Hi, I've just created a market-product that I'd like to publish into the official axonivy-market. 
Can you fork it and review my cool product?

[[link-to-your-product-repo]](https://github.com/ivy-jh/skribble-connector)

cheers
Jens

* * *
⚠️ do not remove this section, but leave it to track the reviewer's work.

# Review Tasks

## Product Domain

- [x] product successfully installs into the Axon Ivy Designer
- [x] product parts are marked as `Connector` or `Demo`
- [x] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...

### Coherent

- [x] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [x] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [x] Html-Dialogs depend on suggested 'frame' template
- [x] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [x] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [x] Tests are implemented that verify, that the product actually runs
- [x] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [x] Depends on standard Axon Ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [x] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [x] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`

## Second Pull request: Description

- [x] the product readme fits into the market landscape
- [x] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` and a German translation for the description section are provided in `[myProduct]/product/Readme_DE.md` .

**Comment by ivy-rew** [comment] 2024-09-04 09:48
when can we expect the on-boarding process to start @ivy-sgi ?

**Comment by ivy-sgi** [comment] 2024-09-04 10:44
Hi @ivy-rew ! There was a public holiday (2 days) in VN - they had a long weekend and started working again today. So I expect to have this in the next 2-3 days.

**Comment by phhung-axonivy** [comment] 2024-09-11 01:21
Hi @ivy-rew
Now, we're starting the review https://github.com/axonivy-market/skribble-connector/pull/1
Thanks for your contribution @ivy-jh

**Comment by ivy-jh** [comment] 2024-10-03 10:08
Thankyou for pulling my project on skribble. 
On the demo tab, there are some images which arent displayed correctly.
![image](https://github.com/user-attachments/assets/fe3856c9-6a97-4e3d-b51f-4c3c76754979)

**Comment by ivy-rew** [comment] 2024-10-10 09:39
any news here? @phhung-axonivy 
I don't understand why the issue is still kept open ... to me it seems as if you checked all tasks :thinking: 

fyi @ivy-sgi

**Comment by phhung-axonivy** [comment] 2024-10-10 09:48
Hi @ivy-rew 
Thanks for your reminder.
I keep this issue open because some images are broken in Demo tab that @ivy-jh reported above.
This problem is resolved yesterday.
Now, I will close this issue.

**Closed by phhung-axonivy** 2024-10-10 09:48 UTC

**Comment by ivy-rew** [comment] 2024-10-10 09:49
> Hi @ivy-rew Thanks for your reminder. I keep this issue open because some images are broken in Demo tab that @ivy-jh reported above. This problem is resolved yesterday. Now, I will close this issue.

Thank you for the clarification; glad to see the issues count decreasing :sweat_smile:
